blog/urls.py
from django.urls import path

from blog.apps import BlogPostConfig
from blog.views import BlogpostCreateView, BlogpostListView, BlogpostUpdateView, BlogpostDetailView, BlogpostDeleteView

app_name = BlogPostConfig.name

urlpatterns = [
    path('create/', BlogpostCreateView.as_view(), name='create'),
    path('', BlogpostListView.as_view(), name='list'),
    path('view/<int:pk>', BlogpostDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogpostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogpostDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import IndexView, ProductListView, ContactView, ProductCreateView
from catalog.views import ProductDetailView, ProductUpdateView, ProductDeleteView, AccessErrorView
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('403error/', AccessErrorView.as_view(), name='access_error'),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls'))
]

config/urls.py
from django.urls import path
from catalog.views import index
from django.conf.urls.static import static
from django.conf import settings

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


class Category(models.Model):
    """Категория товара"""
    title = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    """Продукт"""
    title = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    preview = models.ImageField(upload_to='products/', null=True, blank=True, verbose_name='Изображение')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    price = models.PositiveIntegerField(verbose_name='Цена за покупку')
    created_by = models.ForeignKey('users.User', on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Автор')
    date = models.DateField(verbose_name='Дата создания')
    last_update = models.DateField(verbose_name='Дата последнего изменения')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Contacts(models.Model):
    """Контакты пиццерии"""
    phone_delivery = models.CharField(max_length=50, verbose_name='Телефон доставки')
    phone_ceo = models.CharField(max_length=50, verbose_name='Телефон руководства')
    email = models.CharField(max_length=50, verbose_name='E-mail')

    def __str__(self):
        return f'{self.phone_delivery}, {self.phone_ceo}, {self.email}'

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'


class Version(models.Model):
    """Версия продукта"""
    number = models.PositiveSmallIntegerField(verbose_name='Номер')
    title = models.CharField(max_length=100, verbose_name='Наименование')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='Продукт')
    is_active = models.BooleanField(verbose_name='Признак текущей версии')

    def __str__(self):
        return f'{self.number}: {self.title}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class ProductForm(forms.ModelForm):
    """Форма для создания/редактирования продукта"""
    class Meta:
        model = Product
        exclude = ('created_by',)

    def __init__(self, *args, **kwargs):  # стилизация формы
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_title(self):  # ограничение на использование слов в названии продукта
        prohibited_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                            'радар']
        cleaned_data = self.cleaned_data['title']
        for word in prohibited_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f"Название продукта не может содержать слово: {word}")
        return cleaned_data

    def clean_description(self):  # ограничение на использование слов в описании продукта
        prohibited_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                            'радар']
        cleaned_data = self.cleaned_data['description']
        for word in prohibited_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f"Описание продукта не может содержать слово: {word}")
        return cleaned_data


class VersionForm(forms.ModelForm):
    """Форма для создания/редактирования версии продукта"""
    class Meta:
        model = Version
        fields = "__all__"

    def __init__(self, *args, **kwargs):  # стилизация формы
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_active':
                field.widget.attrs['class'] = 'form-control'

catalog/views.py
from django.shortcuts import render, redirect
from django.views import View
from catalog.models import Product, Contacts, Version
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy
from catalog.forms import ProductForm, VersionForm
from django.forms import inlineformset_factory

from catalog.services import get_cashed_category_list


class AccessRightsMixinView(View):
    """Миксин ограничения доступа для неавторизованных пользователей"""

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('catalog:access_error')
        return super().dispatch(request, *args, **kwargs)


class IndexView(TemplateView):
    """Контроллер просмотра домашней страницы"""
    template_name = 'catalog/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        print(Product.objects.all().order_by('-date')[:5])  # вывод в консоль последних 5 продуктов
        context_data['object_list'] = Product.objects.all()
        context_data['category_list'] = get_cashed_category_list()
        return context_data


class ContactView(TemplateView):
    """Контроллер просмотра контактов"""
    template_name = 'catalog/contact.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Contacts.objects.all().order_by('-id')[:1]  # актуальные контактные данные
        return context_data

    def post(self, request):  # добавление метода post
        if self.request.method == 'POST':
            name = self.request.POST.get('name')
            phone = self.request.POST.get('phone')
            message = self.request.POST.get('message')
            print(f'You have new message from {name}({phone}): {message}')  # вывод информации в консоль
        return render(request, 'catalog/contact.html', self.extra_context)


class ProductListView(ListView):
    """Контроллер просмотра списка продуктов"""
    model = Product
    paginate_by = 9  # количество элементов на одну страницу


class ProductCreateView(AccessRightsMixinView, CreateView):
    """Контроллер создания продукта"""
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):  # автоматическое формирование автора продукта
        if form.is_valid():
            product = form.save()
            product.created_by = self.request.user
            product.save()

        return super().form_valid(form)


class ProductUpdateView(AccessRightsMixinView, UpdateView):
    """Контроллер редактирования продукта"""
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, **kwargs):  # формирование формсета с версиями продукта
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        # проверка наличия единственной активной версии у продукта
        active_versions = Version.objects.filter(product=self.object, is_active=True)
        if active_versions.count() > 1:
            form.add_error(None, 'Выберите только одну активную версию')
            return self.form_invalid(form)

        return super().form_valid(form)


class ProductDetailView(DetailView):
    """Контроллер просмотра отдельного продукта"""
    model = Product


class ProductDeleteView(AccessRightsMixinView, DeleteView):
    """Контроллер удаления продукта"""
    model = Product
    success_url = reverse_lazy('catalog:product_list')


class AccessErrorView(TemplateView):
    """Контроллер ошибки доступа"""
    template_name = 'catalog/access_error.html'

catalog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>B&F</title>

</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h1 class="my-0 mr-md-auto font-weight-normal">B&F</h1>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Сatalog</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Сontacts</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">B&F</h1>
    <p class="lead">B&F - this is a great selection of unlimited beer and fish for a month</p>
</div>

<div class="container">

    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                B&F
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Category's</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Яблоки</a></li>
                    <li><a class="text-muted" href="#">Макароны</a></li>
                    <li><a class="text-muted" href="#">Сахар</a></li>
                    <li><a class="text-muted" href="#">Соль</a></li>
                    <li><a class="text-muted" href="#">Килька</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Additionally</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">We write</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About Us</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Сontacts</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                        <th scope="col">Телефон доставки</th>
                        <th scope="col">Телефон руководства</th>
                        <th scope="col">E-mail</th>
                        </tr>
                        </thead>
                       {% for object in object_list %}
                       <tbody>
                       <tr>
                       <td>{{ object.phone_delivery}}</td>
                       <td>{{ object.phone_сeo}}</td>
                       <td>{{ object.email}}</td>
                       </tr>
                       </tbody>
                      {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Заказать звонок</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                            <button type="submit" name="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Каталог продуктов магазина Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>

    </nav>
</div>
<main>
    <div class="album bg-body-tertiary">
        <div class="container py-5">
            <div class="row">
                {% for object in object_list %}

                <div class="col-md-4">

                    <div class="card mb-4 shadow-sm">
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                        <div class="card-body">
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </div>
                                <small class="text-body-secondary">9 mins</small>
                            </div>
                        </div>
                    </div>

                </div>
                {% endfor %}
            </div>
        </div>
    </div>



</main>
<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">В начало каталога</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

</body>
</html>

catalog/templates/index.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Пицца Boss</h1>
    <p class="lead fst-italic">Горячая итальянская пицца с бесплатной доставкой в твоем городе
    </p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow" style="height :400px;">
                <div class="card-body">
                    <h3 class="card-title">Наши преимущества:</h3>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li> -Доставка до 30 минут в любой район твоего города</li>
                        <li> -Круглосуточная бесплатная доставка</li>
                        <li> -Скидка 10% при регистрации на сайте</li>
                        <li> -Бесплатная пицца при опоздании курьера</li>
                    </ul>
                    <a href="{% url 'users:register' %}" class="btn btn-lg btn-block btn-outline-primary">Зарегистрироваться</a>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card mb-4 box-shadow" style="height :400px;">
                <div class="card-body">
                    <h3 class="card-title">Категории</h3>
                         <ul class="list-unstyled mt-5 mb-5 text-small m-5 fs-5">
                             {% for category in category_list %}
                             <li> {{ category }}</li>
                             {% endfor %}
                         </ul>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Оформить заказ</button>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card mb-4 box-shadow" style="height :400px; width :600px;">
                <div class="card-body">
                    <h3 class="card-title">Сегодня в продаже:</h3>
                    <div id="carousel" class="carousel slide carousel-dark" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            {% for object in object_list %}
                                {% if forloop.first %}
                                   <div class="carousel-item active" data-bs-interval="3000">
                                       <img class="d-block w-50 h-30" src="{% mediapath object.preview %}" alt="{{ object }}"><br/><br/><br/><br/><br/><br/>
                                       <div class="carousel-caption d-none d-md-block">
                                           <div class="text-black mt-1 mb-1"><h5>{{ object }}</h5><p>{{ object.description|truncatechars:100 }}</p></div>
                                       </div>
                                   </div>
                                {% else %}
                                    <div class="carousel-item" data-bs-interval="3000">
                                        <img class="d-block w-50 h-30" src="/media/{{ object.preview }}" alt="{{ object }}"><br/><br/><br/><br/><br/><br/>
                                        <div class="carousel-caption d-none d-md-block">
                                            <div class="text-black"><p style="color:black;"><h5>{{ object }}</h5></p><p>{{ object.description|truncatechars:100 }}</p></div>
                                       </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>

 <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
</body>
</html>

catalog/templates/product.html
{% extends 'catalog/base.html' %}
{% load tags_catalog %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <img src="{% mediapath object_list.image %}" class="rounded mx-auto d-block" alt="preview" height="500">
                <h5 class="card-title">{{ object_list.name }}</h5>
                <p class="card-text">{{ object_list.price }}₽</p>
                <p class="card-text">{{ object_list.about|truncatechars:100 }}</p>
                <p class="card-text">New batch from {{ object_list.updated_at }}</p>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">BUY</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Удалить продукт</h1>
</div>

<div class="container">
    <div class="col-12">
    <div class="row text-start">
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт "{{ object.title }}"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

catalog/templates/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Меню</h1>
</div>

<div class="container">
    <div class="d-flex justify-content-between align-items-center">
        <a href="{% url 'catalog:product_create' %}" class="btn btn-sm btn-outline-danger">Добавить продукт</a>
    </div>
    <br>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

{% for object in object_list %}
    <div class="col">
        <div class="card shadow-sm">
            <img src="{{ object.preview|mediapath }}" />
                <p class="text-center fw-bold">
                    {{ object }}
                    {% for version in object.version_set.all %}
                    {% if version.is_active == True %}
                    <br>Версия: {{ version.number }} "{{ version.title }}"
                    {% endif %}
                    {% endfor%}
                </p>
                    <div class="card-body">
                        <p class="card-text">
                            {{ object.description }}
                        </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="{% url 'catalog:product_detail' object.pk %}" class="btn btn-outline-warning">Подробнее</a>
                                <small class="text-muted">{{ object.price }} руб. </small>
                            </div>
                    </div>
        </div>
    </div>
{% endfor %}
    </div>

        <div id="pages" align="center">

            {% if page_obj.has_previous %}
                <a href="?page={{ page.obj.previous_page_number }}">Предыдущая</a>
            {% endif %}

            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            {% endif %}
        </div>

{% endblock %}